name: CI
on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.17.3

      - name: Check the formatting code
        run: deno fmt -c deno.json --check
        env:
          NO_COLOR: true

      - name: Check the linter
        run: deno lint -c deno.json
        env:
          NO_COLOR: true
